### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by timriffe** [timriffe/AdultCoverage#5]
- [x] add RMSE of age selection to output (mig branch)
- [ ] add r2 of line fit to `ggb()` output (mig branch)
- [x] implement migration in `ggb()` (mig branch) 
- [x] implement migration in `seg()` (mig branch)
- [x] ensure valid use of `mig` in `ggbseg()` (both stages should use mig and in the same way) (mig branch)
- [x] use `mig.summed` flag (mig branch)
- [ ] warn, if total deaths < 25% of population change then either the `deaths.summed` flag is being used wrong or the user should consider not using the method. Use either `message()` or `warning()` (mig branch)
- [ ] add more example data (PJ will send spreadsheets)
- [x] implement seg delta method, but think of a better name for it see RD spreadsheet `AM_SEG_South Africa_males_3_1.xlsx`, calibrate to spirit not values. To iterate or not to iterate?

**Comment by timriffe** [comment]
checked items implemented in mig branch still untested and likely broken
